# Содержание приложения «Глаголы состояния».
# В примерах: {…} — форма состояния (синий), […] — процесс, -ing (оранжевый).

GROUPS = [
    {"ru": "Восприятие", "verbs": "see*, hear, smell*, taste*, feel*, notice, recognise, seem, look*, appear*, sound, resemble"},
    {"ru": "Чувства", "verbs": "like, love, hate, prefer, enjoy*, admire, appreciate, dislike, fear, mind"},
    {"ru": "Желания", "verbs": "want, need, wish, desire, long for"},
    {"ru": "Ум и мнение", "verbs": "know, think*, believe, understand, remember, forget, mean, suppose, doubt, agree, expect*"},
    {"ru": "Отношения и мера", "verbs": "be*, have*, own, belong, contain, consist of, include, involve, depend, cost, weigh*, measure*, matter, lack"},
]

# Двойные глаголы: состояние | процесс
DUAL = [
    ["think", "I think so", "считаю", "I'm thinking about it", "обдумываю"],
    ["have", "has diabetes", "болезнь, владение", "is having a seizure", "событие"],
    ["see", "I see", "понимаю", "I'm seeing a doctor", "на приёме"],
    ["look", "looks pale", "выглядит", "is looking at the scan", "смотрит"],
    ["appear", "appears benign", "по-видимому", "is appearing in court", "появляется"],
    ["weigh", "weighs 82 kg", "весит", "is weighing the patient", "взвешивает"],
    ["measure", "measures 7 mm", "размер", "is measuring the BP", "измеряет"],
    ["taste", "tastes bitter", "на вкус", "is tasting the soup", "пробует"],
    ["smell", "smells strange", "пахнет", "is smelling the milk", "нюхает"],
    ["feel", "feels warm", "на ощупь", "is feeling better", "самочувствие"],
    ["be", "is rude", "характер", "is being rude", "ведёт себя"],
    ["enjoy", "enjoys running", "любит", "is enjoying the trip", "сейчас"],
    ["expect", "I expect so", "думаю", "is expecting a baby", "ждёт"],
]

TOPICS = [
    {"n": 1, "title": "Процесс или состояние",
     "rule": "Continuous показывает процесс: действие идёт и может закончиться. Глаголы состояния описывают то, что просто есть, — знание, желание, чувство, обладание, — поэтому с -ing их не ставят даже в значении «прямо сейчас». Проверка: можно ли остановиться на середине? Осмотр — можно, знание — нет.",
     "ex": [
         {"en": "The doctor [is examining] the patient right now.", "ru": "Врач сейчас осматривает пациента."},
         {"en": "The doctor {knows} this patient well.", "ru": "Врач хорошо знает этого пациента."},
     ]},
    {"n": 2, "title": "Знаю, считаю, помню",
     "rule": "know, believe, understand, remember, forget, mean, suppose, doubt, agree — состояния ума. Они всегда без -ing: Do you understand? — а не Are you understanding? Сюда же think в значении «считать».",
     "ex": [
         {"en": "Do you {understand} the risks of the procedure?", "ru": "Вы понимаете риски процедуры?"},
         {"en": "I {don't remember} his name, but I {know} his face.", "ru": "Не помню его имени, но в лицо знаю."},
         {"en": "Most neurologists now {believe} that the window can be extended.", "ru": "Большинство неврологов теперь считают, что окно можно расширить."},
     ]},
    {"n": 3, "title": "Люблю, хочу, нужно",
     "rule": "like, love, hate, prefer, want, need, wish, mind, appreciate — чувства и желания, тоже состояния: The patient wants to go home, а не is wanting. В разговоре встречается I'm loving it — так подчёркивают яркую эмоцию сейчас, но в письме и в статьях так не пишут.",
     "ex": [
         {"en": "The patient {wants} to go home today.", "ru": "Пациент хочет сегодня домой."},
         {"en": "Many patients {prefer} tablets to injections.", "ru": "Многие пациенты предпочитают таблетки уколам."},
         {"en": "We really {appreciate} your help with the audit.", "ru": "Мы очень ценим вашу помощь с аудитом."},
     ]},
    {"n": 4, "title": "Имею, состою, стою",
     "rule": "own, belong, contain, consist of, include, involve, depend, cost, matter, lack и have в значении «иметь» — отношения, состав и мера. Они описывают, как всё устроено, а не что происходит: each tablet contains 75 mg, it depends on the scan.",
     "ex": [
         {"en": "Each tablet {contains} 75 mg of clopidogrel.", "ru": "Каждая таблетка содержит 75 мг клопидогрела."},
         {"en": "The choice of treatment {depends} on the imaging.", "ru": "Выбор лечения зависит от визуализации."},
         {"en": "The stroke team {consists} of three neurologists and two nurses.", "ru": "Инсультная бригада состоит из трёх неврологов и двух медсестёр."},
     ]},
    {"n": 5, "title": "Вижу, слышу, пахнет",
     "rule": "see, hear, notice, recognise — восприятие без усилия: оно просто случается. «Вижу прямо сейчас» по-английски — can see: I can see a small bleed. Связки smell, taste, feel, sound, look + прилагательное описывают качество: it smells strange, that sounds reasonable.",
     "ex": [
         {"en": "I {can see} a small bleed on the CT, just here.", "ru": "На КТ вижу небольшое кровоизлияние — вот здесь."},
         {"en": "{Can you hear} the murmur?", "ru": "Слышите шум?"},
         {"en": "Your plan {sounds} reasonable.", "ru": "Ваш план звучит разумно."},
     ]},
    {"n": 6, "title": "think: считаю или обдумываю",
     "rule": "think = «считать, полагать» — мнение, состояние: I think it's a TIA. think about / think of = «обдумывать, собираться» — процесс, можно -ing: we're thinking of starting anticoagulation. Спросить мнение — What do you think? Спросить, о чём задумался, — What are you thinking about?",
     "ex": [
         {"en": "I {think} it's a TIA rather than a stroke.", "ru": "Думаю, это ТИА, а не инсульт."},
         {"en": "We [are thinking] of starting anticoagulation next week.", "ru": "Мы думаем начать антикоагуляцию на следующей неделе."},
         {"en": "What {do you think} of the new protocol?", "ru": "Что вы думаете о новом протоколе?"},
     ]},
    {"n": 7, "title": "have: есть или происходит",
     "rule": "have = «иметь»: владение, болезнь, родство, черта — состояние: he has diabetes. В устойчивых сочетаниях have = «делать, переживать»: have lunch, have a shower, have a meeting, have a seizure, have a baby. Это событие, и оно бывает с -ing: she's having a seizure!",
     "ex": [
         {"en": "He {has} type 2 diabetes and hypertension.", "ru": "У него диабет второго типа и гипертония."},
         {"en": "Call the doctor — the patient [is having] a seizure!", "ru": "Зовите врача — у пациента приступ!"},
         {"en": "My sister [is having] a baby in March.", "ru": "Сестра рожает в марте."},
     ]},
    {"n": 8, "title": "see, look, appear",
     "rule": "see = «понимать» или «видеть» — состояние; see = «встречаться, быть на приёме» — действие: I'm seeing a cardiologist on Monday. look = «выглядеть», look like = «быть похожим» — состояние; look at = «смотреть» — действие. appear = «казаться, по-видимому» — состояние; appear = «появляться, выступать» — действие.",
     "ex": [
         {"en": "I {see} what you mean.", "ru": "Понимаю, что вы имеете в виду."},
         {"en": "I [am seeing] a cardiologist on Monday.", "ru": "В понедельник я иду к кардиологу."},
         {"en": "The lesion {appears} to be old, but the surgeon [is looking] at it again.", "ru": "Очаг, по-видимому, старый, но хирург смотрит его ещё раз."},
     ]},
    {"n": 9, "title": "Весит или взвешивает",
     "rule": "Когда глагол описывает свойство — вес, размер, вкус, запах, ощущение на ощупь, — это состояние: the patient weighs 82 kg, the syrup tastes bitter. Когда кто-то совершает действие — взвешивает, измеряет, пробует, нюхает, — это процесс: the nurse is weighing the patient.",
     "ex": [
         {"en": "The patient {weighs} 82 kilograms.", "ru": "Пациент весит 82 килограмма."},
         {"en": "The nurse [is weighing] the patient before thrombolysis.", "ru": "Медсестра взвешивает пациента перед тромболизисом."},
         {"en": "The aneurysm {measures} 7 mm, but the radiologist [is measuring] it again.", "ru": "Аневризма — 7 мм, но рентгенолог перемеряет её."},
     ]},
    {"n": 10, "title": "is или is being",
     "rule": "be обычно описывает постоянное качество: he is aggressive — он агрессивный человек. is being + прилагательное — поведение сейчас, временно и часто вопреки характеру: he is being aggressive today. Типичное применение — упрёк: why are you being so rude?",
     "ex": [
         {"en": "Dr Kim {is} very experienced in thrombectomy.", "ru": "Доктор Ким очень опытна в тромбэктомии."},
         {"en": "He's usually calm, but today he [is being] aggressive with the staff.", "ru": "Обычно он спокоен, но сегодня агрессивен с персоналом."},
     ]},
    {"n": 11, "title": "Когда -ing всё-таки можно",
     "rule": "feel о самочувствии и hurt о боли бывают в обеих формах: How do you feel? = How are you feeling? My back hurts = my back is hurting. В Perfect глаголы состояния берут простую форму: I've known him for years — а не have been knowing.",
     "ex": [
         {"en": "How [are you feeling] today?", "ru": "Как вы себя сегодня чувствуете?"},
         {"en": "My back [is hurting] after the night shift.", "ru": "После ночной смены болит спина."},
         {"en": "I {have known} Dr Smith for ten years.", "ru": "Я знаю доктора Смита десять лет."},
     ]},
    {"n": 12, "title": "Итог — всё вместе",
     "rule": "Пятнадцать случайных карточек из всех тем вперемешку.",
     "ex": []},
]

CARDS = [
    # 1 — процесс или состояние
    {"id": "t1-know", "t": 1, "q": "I ___ the answer, but I'm not allowed to tell you.", "opts": ["know", "am knowing"], "a": "know",
     "why": "know — состояние ума: без -ing даже «прямо сейчас»."},
    {"id": "t1-examine", "t": 1, "q": "Please wait outside — the doctor ___ the patient.", "opts": ["is examining", "examines"], "a": "is examining",
     "why": "Осмотр идёт сейчас и закончится — процесс: is examining."},
    {"id": "t1-understand", "t": 1, "q": "___ what I mean?", "opts": ["Do you understand", "Are you understanding"], "a": "Do you understand",
     "why": "understand — состояние: Do you understand? ✗ Are you understanding?"},
    {"id": "t1-want", "t": 1, "q": "The patient ___ to go home today.", "opts": ["wants", "is wanting"], "a": "wants",
     "why": "want — желание, состояние: wants."},
    {"id": "t1-write", "t": 1, "q": "I can't talk now — I ___ the discharge summary.", "opts": ["am writing", "write"], "a": "am writing",
     "why": "Пишу прямо сейчас — процесс: am writing."},
    {"id": "t1-belong", "t": 1, "q": "This stethoscope ___ to Dr Ivanova.", "opts": ["belongs", "is belonging"], "a": "belongs",
     "why": "belong — отношение, состояние: belongs."},

    # 2 — ум и мнение
    {"id": "t2-believe", "t": 2, "q": "Most neurologists now ___ that the time window can be extended.", "opts": ["believe", "are believing"], "a": "believe",
     "why": "believe — мнение, состояние: believe."},
    {"id": "t2-remember", "t": 2, "q": "I ___ his name — was it Petrov?", "opts": ["don't remember", "am not remembering"], "a": "don't remember",
     "why": "remember — состояние памяти: don't remember."},
    {"id": "t2-mean", "t": 2, "q": "On the chart, NBM ___ “nil by mouth”.", "opts": ["means", "is meaning"], "a": "means",
     "why": "mean = значить — состояние: means."},
    {"id": "t2-suppose", "t": 2, "q": "I ___ we could postpone the scan until Monday.", "opts": ["suppose", "am supposing"], "a": "suppose",
     "why": "suppose = полагать — мнение, без -ing."},
    {"id": "t2-doubt", "t": 2, "q": "I ___ the family will agree to surgery.", "opts": ["doubt", "am doubting"], "a": "doubt",
     "why": "doubt = сомневаться — состояние ума: doubt."},

    # 3 — чувства и желания
    {"id": "t3-prefer", "t": 3, "q": "Many patients ___ oral tablets to injections.", "opts": ["prefer", "are preferring"], "a": "prefer",
     "why": "prefer — предпочтение, состояние: prefer."},
    {"id": "t3-need", "t": 3, "q": "I ___ your signature on the consent form.", "opts": ["need", "am needing"], "a": "need",
     "why": "need — потребность, состояние: need."},
    {"id": "t3-hate", "t": 3, "q": "He ___ hospitals, so try to keep his stay short.", "opts": ["hates", "is hating"], "a": "hates",
     "why": "hate — чувство, состояние: hates."},
    {"id": "t3-appreciate", "t": 3, "q": "We really ___ your help with the audit.", "opts": ["appreciate", "are appreciating"], "a": "appreciate",
     "why": "appreciate = ценить — чувство, без -ing."},
    {"id": "t3-mind", "t": 3, "q": "___ if I open the window?", "opts": ["Do you mind", "Are you minding"], "a": "Do you mind",
     "why": "mind = возражать — состояние: Do you mind…?"},

    # 4 — отношения и мера
    {"id": "t4-contain", "t": 4, "q": "Each tablet ___ 75 mg of clopidogrel.", "opts": ["contains", "is containing"], "a": "contains",
     "why": "contain — состав, состояние: contains."},
    {"id": "t4-depend", "t": 4, "q": "The choice of treatment ___ on the imaging results.", "opts": ["depends", "is depending"], "a": "depends",
     "why": "depend — отношение, состояние: depends."},
    {"id": "t4-cost", "t": 4, "q": "The new scanner ___ over two million roubles.", "opts": ["costs", "is costing"], "a": "costs",
     "why": "cost = стоить (цена) — состояние: costs."},
    {"id": "t4-consist", "t": 4, "q": "The stroke team ___ of three neurologists and two nurses.", "opts": ["consists", "is consisting"], "a": "consists",
     "why": "consist of — состав, состояние: consists of."},
    {"id": "t4-involve", "t": 4, "q": "The procedure ___ a small incision in the groin.", "opts": ["involves", "is involving"], "a": "involves",
     "why": "involve = включать, предполагать — состояние: involves."},
    {"id": "t4-own", "t": 4, "q": "Who ___ this car? It's blocking the ambulance bay.", "opts": ["owns", "is owning"], "a": "owns",
     "why": "own = владеть — состояние: owns."},

    # 5 — восприятие
    {"id": "t5-hear", "t": 5, "q": "Listen — ___ that alarm from the ventilator?", "opts": ["can you hear", "are you hearing"], "a": "can you hear",
     "why": "«Слышу прямо сейчас» — can hear, а не hearing."},
    {"id": "t5-see", "t": 5, "q": "I ___ a small bleed on the CT, just here.", "opts": ["can see", "am seeing"], "a": "can see",
     "why": "«Вижу сейчас» — can see: восприятие, а не процесс."},
    {"id": "t5-smell", "t": 5, "q": "Something ___ strange in the corridor.", "opts": ["smells", "is smelling"], "a": "smells",
     "why": "smell + прилагательное = «пахнет» — качество, без -ing."},
    {"id": "t5-sound", "t": 5, "q": "Your plan ___ reasonable to me.", "opts": ["sounds", "is sounding"], "a": "sounds",
     "why": "sound = звучать, казаться — связка, состояние: sounds."},
    {"id": "t5-recognise", "t": 5, "q": "I ___ this patient — he was here last month.", "opts": ["recognise", "am recognising"], "a": "recognise",
     "why": "recognise = узнавать — восприятие, без -ing."},

    # 6 — think
    {"id": "t6-opinion", "t": 6, "q": "I ___ it's a TIA rather than a stroke.", "opts": ["think", "am thinking"], "a": "think",
     "why": "think = считаю (мнение) — без -ing."},
    {"id": "t6-plan", "t": 6, "q": "We ___ of starting anticoagulation next week.", "opts": ["are thinking", "think"], "a": "are thinking",
     "why": "think of = обдумывать, собираться — процесс: are thinking."},
    {"id": "t6-what", "t": 6, "q": "What ___ of the new protocol?", "opts": ["do you think", "are you thinking"], "a": "do you think",
     "why": "Спрашиваем мнение — What do you think of…?"},
    {"id": "t6-quiet", "t": 6, "q": "You're very quiet. What ___ about?", "opts": ["are you thinking", "do you think"], "a": "are you thinking",
     "why": "О чём задумался прямо сейчас — процесс: What are you thinking about?"},

    # 7 — have
    {"id": "t7-diabetes", "t": 7, "q": "He ___ type 2 diabetes and hypertension.", "opts": ["has", "is having"], "a": "has",
     "why": "have = иметь; болезнь как состояние — has."},
    {"id": "t7-seizure", "t": 7, "q": "Call the doctor — the patient in bed 4 ___ a seizure!", "opts": ["is having", "has"], "a": "is having",
     "why": "Приступ происходит сейчас — have = переживать событие: is having."},
    {"id": "t7-lunch", "t": 7, "q": "Dr Lee ___ lunch — can you call back in ten minutes?", "opts": ["is having", "has"], "a": "is having",
     "why": "have lunch = обедать, сейчас — процесс: is having."},
    {"id": "t7-history", "t": 7, "q": "She ___ a history of atrial fibrillation.", "opts": ["has", "is having"], "a": "has",
     "why": "have a history of — факт, состояние: has."},
    {"id": "t7-baby", "t": 7, "q": "My sister ___ a baby in March.", "opts": ["is having", "has"], "a": "is having",
     "why": "have a baby = родить — событие, договорённость на будущее: is having."},

    # 8 — see, look, appear
    {"id": "t8-see-mean", "t": 8, "q": "I ___ what you mean, but the guidelines say otherwise.", "opts": ["see", "am seeing"], "a": "see",
     "why": "see = понимать — состояние: see."},
    {"id": "t8-see-doctor", "t": 8, "q": "I ___ a cardiologist on Monday about my palpitations.", "opts": ["am seeing", "see"], "a": "am seeing",
     "why": "see = быть на приёме — действие по договорённости: am seeing."},
    {"id": "t8-look-like", "t": 8, "q": "She ___ exactly like her mother.", "opts": ["looks", "is looking"], "a": "looks",
     "why": "look like = быть похожим — состояние: looks."},
    {"id": "t8-look-at", "t": 8, "q": "Why ___ at the monitor? Has something changed?", "opts": ["are you looking", "do you look"], "a": "are you looking",
     "why": "look at = смотреть — действие сейчас: are you looking."},
    {"id": "t8-appear", "t": 8, "q": "The lesion ___ to be at least a week old.", "opts": ["appears", "is appearing"], "a": "appears",
     "why": "appear = казаться, по-видимому — состояние: appears."},

    # 9 — весит или взвешивает
    {"id": "t9-weighs", "t": 9, "q": "The patient ___ 82 kilograms, so the dose is 74 mg.", "opts": ["weighs", "is weighing"], "a": "weighs",
     "why": "weigh = весить — свойство: weighs."},
    {"id": "t9-weighing", "t": 9, "q": "Wait a moment — the nurse ___ the patient before thrombolysis.", "opts": ["is weighing", "weighs"], "a": "is weighing",
     "why": "weigh = взвешивать — действие сейчас: is weighing."},
    {"id": "t9-tastes", "t": 9, "q": "This syrup ___ bitter, so children often refuse it.", "opts": ["tastes", "is tasting"], "a": "tastes",
     "why": "taste + прилагательное = «на вкус» — качество: tastes."},
    {"id": "t9-feels", "t": 9, "q": "The skin over the joint ___ hot and swollen.", "opts": ["feels", "is feeling"], "a": "feels",
     "why": "feel + прилагательное о предмете = «на ощупь» — качество: feels."},
    {"id": "t9-measuring", "t": 9, "q": "Don't talk, please — the nurse ___ your blood pressure.", "opts": ["is measuring", "measures"], "a": "is measuring",
     "why": "measure = измерять — действие сейчас: is measuring."},
    {"id": "t9-measures", "t": 9, "q": "The aneurysm ___ 7 mm in diameter.", "opts": ["measures", "is measuring"], "a": "measures",
     "why": "measure = иметь размер — свойство: measures."},

    # 10 — is или is being
    {"id": "t10-being", "t": 10, "q": "He's usually calm, but today he ___ very aggressive with the staff.", "opts": ["is being", "is"], "a": "is being",
     "why": "Поведение сегодня, вопреки характеру — is being."},
    {"id": "t10-is", "t": 10, "q": "Dr Kim ___ very experienced in thrombectomy.", "opts": ["is", "is being"], "a": "is",
     "why": "Постоянное качество — is."},
    {"id": "t10-silly", "t": 10, "q": "Stop it — you ___ silly.", "opts": ["are being", "are"], "a": "are being",
     "why": "Ведёшь себя глупо сейчас — are being."},
    {"id": "t10-rude", "t": 10, "q": "Why ___ so rude to the nurse?", "opts": ["are you being", "are you"], "a": "are you being",
     "why": "Упрёк за поведение сейчас — are you being rude."},

    # 11 — когда -ing можно; Perfect
    {"id": "t11-known", "t": 11, "q": "I ___ Dr Smith for ten years.", "opts": ["have known", "have been knowing"], "a": "have known",
     "why": "Глагол состояния и в Perfect без Continuous: have known."},
    {"id": "t11-owned", "t": 11, "q": "My family ___ this house since 1990.", "opts": ["has owned", "has been owning"], "a": "has owned",
     "why": "own — состояние: has owned, а не has been owning."},
    {"id": "t11-feel", "t": 11, "q": "How ___ today?", "opts": ["are you feeling", "do you feel"], "a": "are you feeling",
     "also": {"do you feel": "о самочувствии feel бывает в обеих формах"},
     "why": "Обе формы естественны; с -ing звучит теплее и про «сейчас»."},
    {"id": "t11-hurt", "t": 11, "q": "My back ___ after the night shift.", "opts": ["hurts", "is hurting"], "a": "hurts",
     "also": {"is hurting": "о боли hurt бывает в обеих формах"},
     "why": "hurt о боли — обе формы верны; простая звучит нейтральнее."},
]
