# Содержание приложения «Времена».
# В примерах: […] — форма времени (оранжевый), {…} — слово-подсказка (синий).
# В клетках таблицы: {…} — have / had (синий, Perfect), […] — -ing (оранжевый, Continuous).

MIXED_TOPIC = 12
TIMES = [["past", "Past", "прошлое"], ["present", "Present", "настоящее"], ["future", "Future", "будущее"]]
ASPECTS = [
    ["simple", "Simple", "факт, регулярно, по порядку"],
    ["cont", "Continuous", "процесс в момент · be + -ing"],
    ["perf", "Perfect", "результат к моменту · have + V3"],
    ["pc", "Perfect Continuous", "длится до момента · have been + -ing"],
]

TENSES = [
    # ——— настоящее
    {"id": "pres-simple", "time": "present", "aspect": "simple", "name": "Present Simple",
     "cell": "work(s)", "form": "V · he works · do / does",
     "mean": "факт, привычка, регулярно, расписание",
     "marks": "always, usually, often, every day, never",
     "ex": [{"en": "I [work] in the stroke unit.", "ru": "Я работаю в инсультном отделении."},
            {"en": "The ward round [starts] at 8 {every morning}.", "ru": "Обход начинается каждое утро в 8."}],
     "neg": "He doesn't smoke.", "q": "Do you take any tablets?",
     "trap": "«Я работаю здесь 10 лет» — не Present Simple, а Perfect: I've been working here for 10 years.", "topic": 1},
    {"id": "pres-cont", "time": "present", "aspect": "cont", "name": "Present Continuous",
     "cell": "am work[ing]", "form": "am / is / are + -ing",
     "mean": "прямо сейчас; временно, в эти дни; договорился на будущее",
     "marks": "now, at the moment, this week, currently, Look!",
     "ex": [{"en": "The nurse [is taking] his blood pressure {now}.", "ru": "Медсестра сейчас меряет ему давление."},
            {"en": "I['m covering] nights {this week}.", "ru": "На этой неделе я дежурю по ночам."}],
     "neg": "He isn't responding.", "q": "Are you feeling any pain?",
     "trap": "know, want, need, have (иметь) — без -ing: I know, а не I am knowing.", "topic": 1},
    {"id": "pres-perf", "time": "present", "aspect": "perf", "name": "Present Perfect",
     "cell": "{have} worked", "form": "have / has + V3",
     "mean": "результат сейчас; опыт в жизни; «уже», «ещё не»; период не закончился",
     "marks": "already, yet, just, ever, never, so far, this week",
     "ex": [{"en": "The results [have] {just} [come] back.", "ru": "Результаты только что пришли."},
            {"en": "[Have] you {ever} [had] a stroke?", "ru": "У вас когда-нибудь был инсульт?"}],
     "neg": "He hasn't eaten since yesterday.", "q": "Have you taken your tablets?",
     "trap": "С yesterday, ago, in 2019 нельзя — если сказано «когда», нужен Past Simple.", "topic": 2},
    {"id": "pres-pc", "time": "present", "aspect": "pc", "name": "Present Perfect Continuous",
     "cell": "{have} been work[ing]", "form": "have / has been + -ing",
     "mean": "началось в прошлом и длится до сих пор; «сколько уже»; следы процесса",
     "marks": "for, since, how long, all day, lately",
     "ex": [{"en": "I['ve been working] here {for} ten years.", "ru": "Я работаю здесь десять лет."},
            {"en": "{How long} [have] you [been having] these headaches?", "ru": "Как давно у вас эти головные боли?"}],
     "neg": "I haven't been sleeping well.", "q": "How long have you been waiting?",
     "trap": "Русское «работаю уже 10 лет», «болит с понедельника» — это оно, а не Present Simple.", "topic": 3},
    # ——— прошлое
    {"id": "past-simple", "time": "past", "aspect": "simple", "name": "Past Simple",
     "cell": "worked", "form": "V2 · worked, went · did",
     "mean": "закончилось в прошлом; сказано «когда»; события по порядку",
     "marks": "yesterday, ago, last week, in 2019, when…?",
     "ex": [{"en": "He [had] a stroke {two years ago}.", "ru": "У него был инсульт два года назад."},
            {"en": "We [gave] thrombolysis {at 10:40}.", "ru": "Тромболизис провели в 10:40."}],
     "neg": "She didn't lose consciousness.", "q": "When did the symptoms start?",
     "trap": "Вопрос «когда?» — всегда Past Simple: When did it start?", "topic": 2},
    {"id": "past-cont", "time": "past", "aspect": "cont", "name": "Past Continuous",
     "cell": "was work[ing]", "form": "was / were + -ing",
     "mean": "процесс в момент прошлого; фон, на который «упало» событие",
     "marks": "while, when, at 10 pm yesterday, all evening",
     "ex": [{"en": "He [was watching] TV {when} his arm went weak.", "ru": "Он смотрел телевизор, когда ослабла рука."},
            {"en": "{At midnight} I [was] still [writing] notes.", "ru": "В полночь я ещё писал записи."}],
     "neg": "She wasn't wearing a seatbelt.", "q": "What were you doing when it started?",
     "trap": "Цепочка событий — не Continuous: He fell, hit his head and lost consciousness.", "topic": 5},
    {"id": "past-perf", "time": "past", "aspect": "perf", "name": "Past Perfect",
     "cell": "{had} worked", "form": "had + V3",
     "mean": "случилось раньше другого момента в прошлом",
     "marks": "by the time, before, already, after, when",
     "ex": [{"en": "{By the time} he arrived, the window [had closed].", "ru": "Когда он доехал, терапевтическое окно уже закрылось."},
            {"en": "She [had stopped] her warfarin a week {before} the stroke.", "ru": "За неделю до инсульта она бросила варфарин."}],
     "neg": "He hadn't taken his tablets.", "q": "Had she had a seizure before?",
     "trap": "Это не «давно прошедшее», а «раньше другого прошлого»: нужны два момента.", "topic": 6},
    {"id": "past-pc", "time": "past", "aspect": "pc", "name": "Past Perfect Continuous",
     "cell": "{had} been work[ing]", "form": "had been + -ing",
     "mean": "процесс длился до момента в прошлом; «сколько уже тогда»",
     "marks": "for, since, how long — до момента в прошлом",
     "ex": [{"en": "He [had been feeling] dizzy {for} two days before he came in.", "ru": "У него два дня кружилась голова, прежде чем он обратился."},
            {"en": "We [had been waiting] {for} an hour when the scanner broke down.", "ru": "Мы ждали уже час, когда сломался томограф."}],
     "neg": "She hadn't been sleeping.", "q": "How long had he been drinking?",
     "trap": "Как Present Perfect Continuous, только точка отсчёта — в прошлом.", "topic": 6},
    # ——— будущее
    {"id": "fut-simple", "time": "future", "aspect": "simple", "name": "Future Simple",
     "cell": "will work", "form": "will + V",
     "mean": "решаю прямо сейчас; прогноз; обещание",
     "marks": "tomorrow, next week, I think, probably, soon",
     "ex": [{"en": "I['ll call] the family {now}.", "ru": "Сейчас позвоню родственникам."},
            {"en": "You['ll feel] a sharp scratch.", "ru": "Сейчас будет укол."}],
     "neg": "It won't hurt.", "q": "Will I be able to drive?",
     "trap": "После when, if, as soon as — не will: When he comes, I'll call.", "topic": 7},
    {"id": "fut-cont", "time": "future", "aspect": "cont", "name": "Future Continuous",
     "cell": "will be work[ing]", "form": "will be + -ing",
     "mean": "будет в процессе в момент будущего",
     "marks": "this time tomorrow, at 9 tomorrow, all day tomorrow",
     "ex": [{"en": "{This time tomorrow} I['ll be flying] to Moscow.", "ru": "Завтра в это время я буду лететь в Москву."},
            {"en": "Don't call {at 9} — I['ll be doing] the ward round.", "ru": "Не звони в 9 — у меня будет обход."}],
     "neg": "I won't be working on Sunday.", "q": "Will you be using the room this afternoon?",
     "trap": "Вежливый вопрос о планах: Will you be using the scanner? — мягче, чем Will you use…?", "topic": 9},
    {"id": "fut-perf", "time": "future", "aspect": "perf", "name": "Future Perfect",
     "cell": "will {have} worked", "form": "will have + V3",
     "mean": "будет сделано к моменту в будущем",
     "marks": "by Friday, by then, by the end of…",
     "ex": [{"en": "The results [will have come] back {by Monday}.", "ru": "К понедельнику результаты уже придут."},
            {"en": "{By 2030} I [will have worked] here for twenty years.", "ru": "К 2030 году я проработаю здесь двадцать лет."}],
     "neg": "He won't have finished by then.", "q": "Will you have finished the audit by May?",
     "trap": "Главный признак — by + срок.", "topic": 9},
    {"id": "fut-pc", "time": "future", "aspect": "pc", "name": "Future Perfect Continuous",
     "cell": "will {have} been work[ing]", "form": "will have been + -ing",
     "mean": "сколько процесс будет длиться к моменту в будущем",
     "marks": "for … by, in May, by then",
     "ex": [{"en": "{In May} I['ll have been working] here for ten years.", "ru": "В мае будет десять лет, как я здесь работаю."},
            {"en": "{By 6 pm} she['ll have been operating] for eight hours.", "ru": "К шести вечера она будет оперировать уже восемь часов."}],
     "neg": "", "q": "",
     "trap": "Редкое время, сверх уровня: достаточно узнавать.", "topic": 9, "rare": True},
]

# Ловушки русскоговорящих: по-русски | по-английски | почему
TRAPS = [
    ["Я работаю здесь 10 лет.", "I['ve been working] here {for} 10 years.", "длится до сих пор — Perfect Continuous, не Present Simple"],
    ["Я видел его вчера.", "I [saw] him {yesterday}.", "есть «когда» — Past Simple, не Present Perfect"],
    ["Я знаю его давно.", "I['ve known] him {for years}.", "know — глагол состояния: Perfect без -ing"],
    ["Когда он придёт, я позвоню.", "{When} he [comes], I['ll call].", "после when — Present, не will"],
    ["Завтра я встречаюсь с семьёй пациента.", "I['m meeting] the family {tomorrow}.", "договорились — Present Continuous"],
    ["Когда я пришёл, он уже ушёл.", "When I arrived, he [had] {already} [left].", "что было раньше — Past Perfect"],
]

# Слова-подсказки: слова | время
MARKERS = [
    ["always, usually, every day", "Present Simple"],
    ["now, at the moment, this week", "Present Continuous"],
    ["yesterday, ago, last…, in 2019", "Past Simple"],
    ["while, at 10 pm yesterday", "Past Continuous"],
    ["already, yet, just, ever, never", "Present Perfect"],
    ["for, since, how long", "Perfect (Continuous)"],
    ["by the time, before — в прошлом", "Past Perfect"],
    ["tomorrow, next…, I think", "will"],
    ["this time tomorrow", "Future Continuous"],
    ["by Friday, by then", "Future Perfect"],
]

# Будущее: способ | когда | пример
FUTURE = [
    ["will", "решаю прямо сейчас, прогноз, обещание", "I['ll call] the family."],
    ["be going to", "план, решил заранее; видно по признакам", "We['re going to repeat] the scan."],
    ["Present Continuous", "договорились, есть в календаре", "I['m meeting] the family at 3."],
    ["Present Simple", "расписание", "The clinic [opens] at 8."],
]

# Частые ошибки: неверно | верно | почему
ERRORS = [
    ["I work here since 2015", "I've worked here since 2015", "since — Present Perfect"],
    ["I have seen him yesterday", "I saw him yesterday", "yesterday — Past Simple"],
    ["How long do you have this pain?", "How long have you had this pain?", "«как давно» — Present Perfect"],
    ["I am knowing him for years", "I've known him for years", "know — без -ing"],
    ["When he will come, I'll call", "When he comes, I'll call", "после when — без will"],
    ["He has died in 2019", "He died in 2019", "дата — Past Simple"],
]

TOPICS = [
    {"n": 1, "title": "Present Simple или Continuous",
     "rule": "Present Simple — факт, привычка, регулярно, расписание: He smokes twenty a day. Present Continuous — прямо сейчас или временно, в эти дни: The doctor is examining the patient. Подсказки: always, usually, every day — Simple; now, at the moment, this week, Look! — Continuous.",
     "ex": [
         {"en": "He [smokes] twenty cigarettes {a day}.", "ru": "Он выкуривает двадцать сигарет в день."},
         {"en": "The nurse [is taking] his blood pressure {now}.", "ru": "Медсестра сейчас меряет ему давление."},
     ]},
    {"n": 2, "title": "Past Simple или Present Perfect",
     "rule": "По-русски одно прошедшее, по-английски два. Сказано или понятно, когда — yesterday, ago, last week, in 2019 — Past Simple: He had a stroke in 2019. Время не названо, важен результат сейчас или опыт — Present Perfect: He has had two strokes. Вопрос «когда?» — только Past Simple: When did it start?",
     "ex": [
         {"en": "He [had] a stroke {in 2019}.", "ru": "У него был инсульт в 2019 году."},
         {"en": "He['s had] two strokes {so far}.", "ru": "У него уже было два инсульта."},
         {"en": "{When} [did] the weakness [start]?", "ru": "Когда началась слабость?"},
     ]},
    {"n": 3, "title": "for и since: «сколько уже»",
     "rule": "Русское настоящее «работаю здесь 10 лет», «болеет с понедельника» по-английски — Present Perfect или Perfect Continuous: I've been working here for ten years. for — сколько времени (for ten years), since — с какого момента (since 2015). How long…? — тоже Perfect: How long have you had this pain?",
     "ex": [
         {"en": "I['ve been working] here {for} ten years.", "ru": "Я работаю здесь десять лет."},
         {"en": "He['s been] in hospital {since} Monday.", "ru": "Он в больнице с понедельника."},
         {"en": "{How long} [have] you [had] this pain?", "ru": "Как давно у вас эта боль?"},
     ]},
    {"n": 4, "title": "Perfect или Perfect Continuous",
     "rule": "Present Perfect — результат, сколько сделано: I've written three discharge summaries. Present Perfect Continuous — сам процесс, как долго, его следы: I've been writing summaries all morning; Why are you out of breath? — I've been running. Глаголы состояния (know, be, have — иметь) — только Perfect: I've known him for years.",
     "ex": [
         {"en": "I['ve written] three discharge summaries {today}.", "ru": "Сегодня я написал три выписки."},
         {"en": "I['ve been writing] summaries {all morning}.", "ru": "Всё утро пишу выписки."},
     ]},
    {"n": 5, "title": "Past Simple или Past Continuous",
     "rule": "Past Continuous — фон, процесс в момент прошлого; Past Simple — событие, которое «упало» на этот фон: He was watching TV when his arm went weak. while + Continuous — процесс идёт одновременно с другим. Цепочка событий по порядку — только Past Simple: He fell, hit his head and lost consciousness.",
     "ex": [
         {"en": "He [was watching] TV {when} his arm [went] weak.", "ru": "Он смотрел телевизор, когда ослабла рука."},
         {"en": "{While} I [was examining] him, he [had] a seizure.", "ru": "Пока я его осматривал, у него случился приступ."},
         {"en": "He [fell], [hit] his head and [lost] consciousness.", "ru": "Он упал, ударился головой и потерял сознание."},
     ]},
    {"n": 6, "title": "Past Perfect: что было раньше",
     "rule": "Past Perfect (had + V3) — что случилось раньше другого момента в прошлом: By the time the ambulance arrived, he had regained consciousness. Подсказки: by the time, before, already, when. Past Perfect Continuous (had been + -ing) — процесс длился до того момента: He had been feeling dizzy for two days.",
     "ex": [
         {"en": "{By the time} he arrived, the window [had closed].", "ru": "Когда он доехал, терапевтическое окно уже закрылось."},
         {"en": "He [had been feeling] dizzy {for} two days before he came in.", "ru": "У него два дня кружилась голова, прежде чем он обратился."},
     ]},
    {"n": 7, "title": "Будущее: will, going to и другие",
     "rule": "will — решаю прямо сейчас, прогноз, обещание: I'll get it. be going to — план, решил заранее, или видно по признакам: He's going to be sick! Present Continuous — договорились, есть в календаре: I'm meeting the family at 3. Present Simple — расписание: The clinic opens at 8.",
     "ex": [
         {"en": "The phone's ringing. — I['ll get] it.", "ru": "Телефон звонит. — Я возьму."},
         {"en": "We['re going to repeat] the scan tomorrow.", "ru": "Завтра мы повторим КТ — уже решили."},
         {"en": "I['m meeting] the family {at 3}.", "ru": "В три я встречаюсь с родственниками."},
     ]},
    {"n": 8, "title": "После when, if — без will",
     "rule": "В частях с when, if, as soon as, before, after, until будущее выражают Present: When the results come, I'll call you — а не when the results will come. Если важно «уже сделано к тому моменту» — Present Perfect: I'll send it when I've finished.",
     "ex": [
         {"en": "I['ll call] you {as soon as} the results [come] back.", "ru": "Позвоню, как только придут результаты."},
         {"en": "{When} I['ve finished] the round, I['ll ring] you.", "ru": "Когда закончу обход, позвоню."},
     ]},
    {"n": 9, "title": "Future Continuous и Future Perfect", "late": 0.3,
     "rule": "Future Continuous (will be + -ing) — будет в процессе в момент будущего: This time tomorrow I'll be flying to Moscow. Future Perfect (will have + V3) — будет сделано к моменту: The results will have come back by Monday. Подсказки: this time tomorrow — Continuous; by Monday, by then — Perfect.",
     "ex": [
         {"en": "{This time tomorrow} I['ll be flying] to Moscow.", "ru": "Завтра в это время я буду лететь в Москву."},
         {"en": "The results [will have come] back {by Monday}.", "ru": "К понедельнику результаты уже придут."},
     ]},
    {"n": 10, "title": "Глаголы состояния — без -ing",
     "rule": "know, want, believe, understand, need, own, seem и have в значении «иметь» не ставят в Continuous, даже «прямо сейчас» и даже с for: I know, I want, I've known him for years. Подробно — в приложении «Глаголы состояния».",
     "ex": [
         {"en": "I [know] what you mean.", "ru": "Я понимаю, что вы имеете в виду."},
         {"en": "I['ve known] him {for} twenty years.", "ru": "Я знаю его двадцать лет."},
     ]},
    {"n": 11, "title": "Узнай время",
     "rule": "Смотри на форму — называй время. have + V3 — Perfect, be + -ing — Continuous, have been + -ing — Perfect Continuous; had — прошлое, will — будущее. Узнавание закрепляет таблицу.",
     "ex": []},
    {"n": MIXED_TOPIC, "title": "Итог — всё вместе",
     "rule": "Пятнадцать случайных карточек из всех тем вперемешку.",
     "ex": []},
]

CARDS = [
    # 1 — Present Simple / Continuous
    {"id": "a-smoke", "t": 1, "q": "He ___ about twenty cigarettes a day.", "opts": ["smokes", "is smoking"], "a": "smokes",
     "why": "Привычка, a day — Present Simple."},
    {"id": "a-now", "t": 1, "q": "Please wait outside — the doctor ___ the patient right now.", "opts": ["is examining", "examines"], "a": "is examining",
     "why": "right now — Present Continuous."},
    {"id": "a-round", "t": 1, "q": "The ward round ___ at 8 every morning.", "opts": ["starts", "is starting"], "a": "starts",
     "why": "Расписание, every morning — Present Simple."},
    {"id": "a-week", "t": 1, "q": "___ nights this week, so I can't come to the meeting.", "opts": ["I'm working", "I work"], "a": "I'm working",
     "why": "this week — временно: Present Continuous."},
    {"id": "a-look", "t": 1, "q": "Look! The patient ___ to get out of bed.", "opts": ["is trying", "tries"], "a": "is trying",
     "why": "Look! — прямо сейчас: Present Continuous."},
    {"id": "a-always", "t": 1, "q": "She always ___ her tablets with breakfast.", "opts": ["takes", "is taking"], "a": "takes",
     "why": "always — привычка: Present Simple."},

    # 2 — Past Simple / Present Perfect
    {"id": "b-2019", "t": 2, "q": "He ___ in 2019.", "opts": ["died", "has died"], "a": "died",
     "why": "in 2019 — «когда» названо: Past Simple."},
    {"id": "b-sofar", "t": 2, "q": "He ___ two strokes so far.", "opts": ["has had", "had"], "a": "has had",
     "why": "so far — до сих пор: Present Perfect."},
    {"id": "b-when", "t": 2, "q": "When ___ the symptoms start?", "opts": ["did", "have"], "a": "did",
     "why": "Вопрос «когда?» — Past Simple."},
    {"id": "b-first", "t": 2, "q": "It's the first time I ___ a case like this.", "opts": ["have seen", "saw"], "a": "have seen",
     "why": "It's the first time — Present Perfect."},
    {"id": "b-yet", "t": 2, "q": "I ___ the discharge summary yet.", "opts": ["haven't written", "didn't write"], "a": "haven't written",
     "why": "yet — Present Perfect."},
    {"id": "b-ago", "t": 2, "q": "He ___ his arm ten minutes ago, but now it's weak again.", "opts": ["moved", "has moved"], "a": "moved",
     "why": "ago — Past Simple."},
    {"id": "b-night", "t": 2, "q": "___ the news last night?", "opts": ["Did you see", "Have you seen"], "a": "Did you see",
     "why": "last night — Past Simple."},
    {"id": "b-yesterday", "t": 2, "q": "I ___ to the family yesterday.", "opts": ["spoke", "have spoken"], "a": "spoke",
     "why": "yesterday — Past Simple."},

    # 3 — for / since
    {"id": "c-work", "t": 3, "q": "I ___ here for ten years.", "opts": ["have been working", "work", "am working"], "a": "have been working",
     "why": "Длится до сих пор + for — Perfect Continuous. I work here for 10 years — ошибка."},
    {"id": "c-icu", "t": 3, "q": "She ___ in intensive care since Monday.", "opts": ["has been", "is", "was"], "a": "has been",
     "why": "since + до сих пор — Present Perfect."},
    {"id": "c-howlong", "t": 3, "q": "How long ___ this pain?", "opts": ["have you had", "do you have", "are you having"], "a": "have you had",
     "why": "«Как давно» — Present Perfect."},
    {"id": "c-for", "t": 3, "q": "He's been in hospital ___ two weeks.", "opts": ["for", "since"], "a": "for",
     "why": "Сколько времени — for."},
    {"id": "c-since", "t": 3, "q": "I've known him ___ 2010.", "opts": ["since", "for"], "a": "since",
     "why": "С какого момента — since."},
    {"id": "c-known", "t": 3, "q": "I ___ Dr Petrova for years.", "opts": ["have known", "have been knowing", "know"], "a": "have known",
     "why": "know — глагол состояния: Perfect без -ing."},

    # 4 — Perfect / Perfect Continuous
    {"id": "d-three", "t": 4, "q": "I ___ three discharge summaries today.", "opts": ["have written", "have been writing"], "a": "have written",
     "why": "Сколько сделано — Present Perfect."},
    {"id": "d-morning", "t": 4, "q": "I'm exhausted — I ___ discharge summaries all morning.", "opts": ["have been writing", "have written"], "a": "have been writing",
     "why": "Процесс, как долго, устал от него — Perfect Continuous."},
    {"id": "d-running", "t": 4, "q": "Why are you out of breath? — ___.", "opts": ["I've been running", "I've run"], "a": "I've been running",
     "why": "Видны следы процесса — Perfect Continuous."},
    {"id": "d-howmany", "t": 4, "q": "How many patients ___ this morning?", "opts": ["have you seen", "have you been seeing"], "a": "have you seen",
     "why": "How many — результат: Present Perfect."},
    {"id": "d-waiting", "t": 4, "q": "How long ___ for the ambulance?", "opts": ["have you been waiting", "have you waited"], "a": "have you been waiting",
     "why": "Как долго длится — Perfect Continuous."},

    # 5 — Past Simple / Past Continuous
    {"id": "e-tv", "t": 5, "q": "He ___ TV when his arm suddenly went weak.", "opts": ["was watching", "watched"], "a": "was watching",
     "why": "Фон, процесс — Past Continuous."},
    {"id": "e-went", "t": 5, "q": "He was watching TV when his arm suddenly ___ weak.", "opts": ["went", "was going"], "a": "went",
     "why": "Событие на фоне — Past Simple."},
    {"id": "e-while", "t": 5, "q": "While I ___ him, he had a seizure.", "opts": ["was examining", "examined"], "a": "was examining",
     "why": "while + процесс — Past Continuous."},
    {"id": "e-chain", "t": 5, "q": "He fell, ___ his head and lost consciousness.", "opts": ["hit", "was hitting"], "a": "hit",
     "why": "Цепочка событий — Past Simple."},
    {"id": "e-doing", "t": 5, "q": "What ___ when the symptoms started?", "opts": ["were you doing", "did you do"], "a": "were you doing",
     "why": "Что было в процессе в тот момент — Past Continuous."},
    {"id": "e-driving", "t": 5, "q": "She ___ home from work when the headache started.", "opts": ["was driving", "drove"], "a": "was driving",
     "why": "Фон для события — Past Continuous."},

    # 6 — Past Perfect
    {"id": "f-regained", "t": 6, "q": "By the time the ambulance arrived, he ___ consciousness.", "opts": ["had regained", "has regained", "regains"], "a": "had regained",
     "why": "by the time — раньше другого прошлого: Past Perfect."},
    {"id": "f-stopped", "t": 6, "q": "She ___ her warfarin a week before the stroke.", "opts": ["had stopped", "has stopped", "stops"], "a": "had stopped",
     "why": "Раньше инсульта — Past Perfect."},
    {"id": "f-never", "t": 6, "q": "He told us he ___ a seizure before.", "opts": ["had never had", "has never had", "never has"], "a": "had never had",
     "why": "До того момента в прошлом — Past Perfect."},
    {"id": "f-dizzy", "t": 6, "q": "He ___ dizzy for two days before he came in.", "opts": ["had been feeling", "has been feeling", "is feeling"], "a": "had been feeling",
     "why": "Длилось до момента в прошлом — Past Perfect Continuous."},
    {"id": "f-left", "t": 6, "q": "When I got to the ward, the consultant ___.", "opts": ["had already left", "has already left", "already leaves"], "a": "had already left",
     "why": "Ушёл раньше, чем я пришёл, — Past Perfect."},

    # 7 — будущее
    {"id": "g-get", "t": 7, "q": "The phone's ringing. — OK, ___ it.", "opts": ["I'll get", "I'm going to get", "I get"], "a": "I'll get",
     "why": "Решаю прямо сейчас — will."},
    {"id": "g-contrast", "t": 7, "q": "Why have you ordered more contrast? — Because ___ another CT this afternoon.", "opts": ["we're going to do", "we'll do"], "a": "we're going to do",
     "why": "План, решили заранее — going to."},
    {"id": "g-meeting", "t": 7, "q": "I can't come at 3 — ___ the patient's family.", "opts": ["I'm meeting", "I meet", "I'll meet"], "a": "I'm meeting",
     "why": "Договорились, есть в календаре — Present Continuous."},
    {"id": "g-opens", "t": 7, "q": "The outpatient clinic ___ at 8 tomorrow.", "opts": ["opens", "is going to open"], "a": "opens",
     "why": "Расписание — Present Simple."},
    {"id": "g-sick", "t": 7, "q": "Look at him — ___ sick!", "opts": ["he's going to be", "he'll be"], "a": "he's going to be",
     "why": "Видно по признакам — going to."},
    {"id": "g-promise", "t": 7, "q": "Don't worry, ___ you as soon as the results come.", "opts": ["I'll call", "I'm calling", "I call"], "a": "I'll call",
     "why": "Обещание — will."},

    # 8 — после when, if
    {"id": "h-arrives", "t": 8, "q": "I'll call you as soon as the consultant ___.", "opts": ["arrives", "will arrive", "arrived"], "a": "arrives",
     "why": "После as soon as — Present, не will."},
    {"id": "h-until", "t": 8, "q": "Stay in bed until the nurse ___ back.", "opts": ["comes", "will come", "came"], "a": "comes",
     "why": "После until — Present."},
    {"id": "h-finished", "t": 8, "q": "I'll send you the report when I ___ it.", "opts": ["have finished", "will finish", "finished"], "a": "have finished",
     "why": "Уже сделано к тому моменту — Present Perfect; will нельзя."},
    {"id": "h-before", "t": 8, "q": "Take the tablet before you ___ to bed.", "opts": ["go", "will go", "went"], "a": "go",
     "why": "После before — Present."},

    # 9 — Future Continuous / Perfect
    {"id": "i-round", "t": 9, "q": "Don't call at 9 — I ___ the ward round.", "opts": ["will be doing", "will have done", "do"], "a": "will be doing",
     "why": "В процессе в момент будущего — Future Continuous."},
    {"id": "i-friday", "t": 9, "q": "By Friday we ___ all the tests.", "opts": ["will have done", "will be doing", "do"], "a": "will have done",
     "why": "by Friday — будет сделано: Future Perfect."},
    {"id": "i-flying", "t": 9, "q": "This time tomorrow I ___ to Moscow.", "opts": ["will be flying", "will have flown", "fly"], "a": "will be flying",
     "why": "this time tomorrow — Future Continuous."},
    {"id": "i-2030", "t": 9, "q": "By 2030 I ___ here for twenty years.", "opts": ["will have worked", "will work", "will be working"], "a": "will have worked",
     "why": "by 2030 — Future Perfect."},

    # 10 — глаголы состояния
    {"id": "j-know", "t": 10, "q": "I ___ what you mean.", "opts": ["know", "am knowing"], "a": "know",
     "why": "know — без -ing."},
    {"id": "j-want", "t": 10, "q": "The patient ___ to go home today.", "opts": ["wants", "is wanting"], "a": "wants",
     "why": "want — без -ing."},
    {"id": "j-known", "t": 10, "q": "I ___ him for twenty years.", "opts": ["have known", "have been knowing", "know"], "a": "have known",
     "why": "for + до сих пор, но know — Perfect без -ing."},
    {"id": "j-have", "t": 10, "q": "He ___ two children.", "opts": ["has", "is having"], "a": "has",
     "why": "have = иметь — без -ing."},

    # 11 — узнай время
    {"id": "k-1", "t": 11, "q": "She has been working here since 2015. → ___", "ru": "Какое это время?", "say": "She has been working here since 2015.",
     "opts": ["Present Perfect Continuous", "Present Perfect", "Past Continuous"], "a": "Present Perfect Continuous",
     "why": "has been + -ing — Present Perfect Continuous."},
    {"id": "k-2", "t": 11, "q": "The results had come back before the round. → ___", "ru": "Какое это время?", "say": "The results had come back before the round.",
     "opts": ["Past Perfect", "Present Perfect", "Past Simple"], "a": "Past Perfect",
     "why": "had + V3 — Past Perfect."},
    {"id": "k-3", "t": 11, "q": "I'll be working late tonight. → ___", "ru": "Какое это время?", "say": "I'll be working late tonight.",
     "opts": ["Future Continuous", "Present Continuous", "Future Simple"], "a": "Future Continuous",
     "why": "will be + -ing — Future Continuous."},
    {"id": "k-4", "t": 11, "q": "He was sleeping when I came in. → ___", "ru": "Какое время у was sleeping?", "say": "He was sleeping when I came in.",
     "opts": ["Past Continuous", "Past Simple", "Present Continuous"], "a": "Past Continuous",
     "why": "was + -ing — Past Continuous."},
    {"id": "k-5", "t": 11, "q": "We've already given the dose. → ___", "ru": "Какое это время?", "say": "We've already given the dose.",
     "opts": ["Present Perfect", "Past Simple", "Past Perfect"], "a": "Present Perfect",
     "why": "have + V3 — Present Perfect."},
    {"id": "k-6", "t": 11, "q": "By Monday we'll have finished the audit. → ___", "ru": "Какое это время?", "say": "By Monday we'll have finished the audit.",
     "opts": ["Future Perfect", "Future Simple", "Present Perfect"], "a": "Future Perfect",
     "why": "will have + V3 — Future Perfect."},
    {"id": "k-7", "t": 11, "q": "The nurse is changing the dressing. → ___", "ru": "Какое это время?", "say": "The nurse is changing the dressing.",
     "opts": ["Present Continuous", "Present Simple", "Past Continuous"], "a": "Present Continuous",
     "why": "is + -ing — Present Continuous."},
    {"id": "k-8", "t": 11, "q": "He had a stroke last year. → ___", "ru": "Какое это время?", "say": "He had a stroke last year.",
     "opts": ["Past Simple", "Present Perfect", "Past Perfect"], "a": "Past Simple",
     "why": "had здесь — просто прошедшее от have: Past Simple."},
]
