# Содержание приложения «10 ошибок»: самые частые ошибки русскоговорящих на пути от B1 к B2.
# В парах: |…| — то, что исправили (зелёный).

MIXED_TOPIC = 11

# Чек-лист: короткая проверка | пример
CHECK = [
    ["Перед существительным есть a или the?", "a doctor · the results"],
    ["yesterday, ago — Past; since, for, ever — Perfect", "I saw · I've seen"],
    ["В вопросе есть do, does или did?", "Where do you work?"],
    ["После when и if нет will", "when I finish"],
    ["Отрицание в предложении одно", "I don't know anything"],
    ["want + кого + to", "I want you to check"],
    ["information, advice, news — без a и без -s", "some advice"],
    ["Предлог — английский, а не русский", "explain to me · discuss it"],
    ["Глагол и объект не разрываем", "speak English very well"],
    ["Похожее слово — не всегда то же", "ангина = tonsillitis"],
]

TOPICS = [
    {"n": 1, "title": "Артикли", "bad": "I am doctor.", "good": "I'm a doctor.",
     "why": "В русском артиклей нет, поэтому мозг их просто пропускает. А англичанин фразу без артикля сразу слышит как ошибку.",
     "rule": "Перед исчисляемым существительным в единственном числе артикль нужен всегда: a — один из многих или впервые (a doctor, a headache), the — тот самый, понятно какой (the window, the results). Без артикля — только множественное число или неисчисляемое в общем смысле: Patients need sleep. Life is hard.",
     "pairs": [
         {"bad": "I am doctor.", "good": "I'm |a| doctor.", "ru": "Я врач."},
         {"bad": "Can you open window?", "good": "Can you open |the| window?", "ru": "Можешь открыть окно?"},
         {"bad": "He has headache.", "good": "He has |a| headache.", "ru": "У него болит голова."},
         {"bad": "The life is hard.", "good": "|Life| is hard.", "ru": "Жизнь — непростая штука."},
     ],
     "b2": "The ставим перед превосходной степенью и словами «единственный», «первый»: the best option, the only way, the first time. И когда уточняем, какой именно: the patient in bed 5.",
     "more": "Подробнее — плитки «Артикли» и «Без a/an»."},
    {"n": 2, "title": "Present Perfect или Past", "bad": "I have seen him yesterday.", "good": "I saw him yesterday.",
     "why": "В русском одно прошедшее время: «видел» — и вчера, и вообще в жизни. В английском их два. А «живу здесь пять лет» по-русски звучит в настоящем, по-английски — только have lived.",
     "rule": "Есть момент в прошлом (yesterday, ago, last week, in 2019, вопрос when?) — Past Simple: I saw him yesterday. Момента нет, важны опыт или результат (ever, never, already, yet, just) — Present Perfect: I've seen this before. «Уже N лет, до сих пор» — have + V3 + for или since: I've worked here for ten years.",
     "pairs": [
         {"bad": "I have seen him yesterday.", "good": "I |saw| him yesterday.", "ru": "Я видел его вчера."},
         {"bad": "I work here for five years.", "good": "I|'ve worked| here for five years.", "ru": "Я работаю здесь пять лет."},
         {"bad": "When have you arrived?", "good": "When |did you arrive|?", "ru": "Когда ты приехал?"},
     ],
     "b2": "Для длительности чаще Present Perfect Continuous: I've been waiting for an hour. Вопрос «как долго?» — How long have you been working here?",
     "more": "Подробнее — плитки «Времена» и «gone / been»."},
    {"n": 3, "title": "Вопросы без do", "bad": "Where you work?", "good": "Where do you work?",
     "why": "В русском вопрос делает интонация: «Ты здесь работаешь?» В английском нужен помощник — do, does или did, — и он встаёт перед подлежащим.",
     "rule": "Вопрос: вопросительное слово + do / does / did + подлежащее + глагол: Where do you work? Why didn't you call? «Что значит…?» — What does … mean? Исключение — вопрос к подлежащему «кто? что?»: Who called? What happened? — без did.",
     "pairs": [
         {"bad": "Where you work?", "good": "Where |do you| work?", "ru": "Где ты работаешь?"},
         {"bad": "Why you didn't call?", "good": "Why |didn't you| call?", "ru": "Почему ты не позвонил?"},
         {"bad": "What means TIA?", "good": "What |does| TIA |mean|?", "ru": "Что значит TIA?"},
     ],
     "b2": "Вежливый (косвенный) вопрос — с обычным порядком слов и без do: Could you tell me where the lab is? Do you know what time it starts?",
     "more": ""},
    {"n": 4, "title": "Will после when и if", "bad": "When I will finish…", "good": "When I finish…",
     "why": "По-русски «когда закончу», «если будет» — будущее время. В английском после when, if, until, as soon as, before, after будущее передают настоящим.",
     "rule": "В части с when / if / until / as soon as / before / after — Present Simple, в другой части — will: I'll call you when I finish. If it rains, we'll stay. Will сразу после when и if в значении будущего не ставим.",
     "pairs": [
         {"bad": "When I will finish, I'll call you.", "good": "When I |finish|, I'll call you.", "ru": "Когда закончу, позвоню тебе."},
         {"bad": "If the pain will come back, take this.", "good": "If the pain |comes| back, take this.", "ru": "Если боль вернётся, выпейте это."},
         {"bad": "Wait until the doctor will come.", "good": "Wait until the doctor |comes|.", "ru": "Подождите, пока не придёт врач."},
     ],
     "b2": "Если действие должно сначала завершиться — Present Perfect: I'll call you as soon as I've seen the scan.",
     "more": "Подробнее — плитка «Conditionals»."},
    {"n": 5, "title": "Двойное отрицание", "bad": "I don't know nothing.", "good": "I don't know anything.",
     "why": "По-русски «я ничего не знаю», «никто не пришёл» — два отрицания, и это норма. В английском отрицание в предложении одно.",
     "rule": "Одно отрицание на фразу: I don't know anything = I know nothing. Nobody came (не nobody didn't come). I've never seen it (не haven't never). После not — слова на any-: anything, anyone, anywhere.",
     "pairs": [
         {"bad": "I don't know nothing.", "good": "I don't know |anything|.", "ru": "Я ничего не знаю."},
         {"bad": "Nobody didn't call.", "good": "Nobody |called|.", "ru": "Никто не позвонил."},
         {"bad": "I haven't never seen it.", "good": "I've |never| seen it.", "ru": "Я никогда такого не видел."},
     ],
     "b2": "hardly, barely, rarely — уже «почти не»: I can hardly breathe (не can't hardly). Neither и nor — тоже отрицание: Neither drug helped.",
     "more": ""},
    {"n": 6, "title": "«Хочу, чтобы ты…»", "bad": "I want that you check it.", "good": "I want you to check it.",
     "why": "Русское «хочу, чтобы ты…» тянет за собой that. Но want, would like, need, expect, ask, tell устроены иначе: кого + to + глагол.",
     "rule": "want / would like / need / expect / ask / tell + кого + to + глагол: I want you to check it. She asked me to wait. А после let и make — без to: Let me explain. It made him cough.",
     "pairs": [
         {"bad": "I want that you check the dose.", "good": "I want |you to check| the dose.", "ru": "Я хочу, чтобы ты проверил дозу."},
         {"bad": "Let me to explain.", "good": "Let me |explain|.", "ru": "Позвольте, я объясню."},
         {"bad": "The drug made him to feel sick.", "good": "The drug made him |feel| sick.", "ru": "От лекарства его тошнило."},
     ],
     "b2": "suggest и recommend так не работают: I suggest doing a CT · The doctor recommended that he rest. Suggest you to — ошибка.",
     "more": "Подробнее — плитки «Кого+to do» и «to / -ing»."},
    {"n": 7, "title": "information, advice, news", "bad": "an advice, informations", "good": "some advice, information",
     "why": "По-русски «советы», «новости», «сведения» бывают во множественном числе. В английском information, advice, news, equipment, research, evidence — неисчисляемые.",
     "rule": "Без a и без -s: some information, a lot of advice, the equipment. Один совет — a piece of advice. News — единственное число: The news is good.",
     "pairs": [
         {"bad": "Can you give me an advice?", "good": "Can you give me |some advice|?", "ru": "Можете дать совет?"},
         {"bad": "Thanks for the informations.", "good": "Thanks for the |information|.", "ru": "Спасибо за информацию."},
         {"bad": "The news are bad.", "good": "The news |is| bad.", "ru": "Новости плохие."},
     ],
     "b2": "Ещё неисчисляемые, о которые спотыкаются на B2: research, evidence, feedback, progress, knowledge, damage. Одно исследование — a study, а не a research.",
     "more": "Подробнее — плитка «Countable»."},
    {"n": 8, "title": "Предлоги-кальки", "bad": "explain me, discuss about", "good": "explain to me, discuss",
     "why": "Предлог переносят из русского или теряют: «объясни мне» — explain me, «обсудить что-то» превращается в discuss about. У английского глагола свой набор предлогов.",
     "rule": "С предлогом: listen to, wait for, explain sth to sb, depend on, pay for, agree with. Без предлога, хотя в русском он есть: discuss, enter, answer, call, attend, reach.",
     "pairs": [
         {"bad": "Please explain me the results.", "good": "Please explain the results |to me|.", "ru": "Объясните мне, пожалуйста, результаты."},
         {"bad": "We discussed about the plan.", "good": "We |discussed the plan|.", "ru": "Мы обсудили план."},
         {"bad": "I'm waiting you.", "good": "I'm waiting |for| you.", "ru": "Я жду тебя."},
     ],
     "b2": "arrive in (город, страна) и arrive at (здание): arrive at the hospital, никогда не arrive to. Ещё: married to, consist of, suffer from, recover from.",
     "more": "Подробнее — плитки «Предлоги» и «to / for»."},
    {"n": 9, "title": "Порядок слов", "bad": "I very like it.", "good": "I really like it.",
     "why": "В русском порядок слов свободный: «очень люблю», «по-английски хорошо говорит». В английском он жёсткий: кто — что делает — что, а наречия стоят на своих местах.",
     "rule": "Very не ставим перед глаголом: I really like it или I like it very much. Глагол и объект не разрываем: He speaks English very well. Always, often, never, usually — перед основным глаголом, но после be: I often work nights, he is always late. Время и место — в конце: I go there every day.",
     "pairs": [
         {"bad": "I very like this job.", "good": "I |really like| this job.", "ru": "Мне очень нравится эта работа."},
         {"bad": "He speaks very well English.", "good": "He speaks |English very well|.", "ru": "Он очень хорошо говорит по-английски."},
         {"bad": "Always I drink coffee.", "good": "I |always drink| coffee.", "ru": "Я всегда пью кофе."},
     ],
     "b2": "Если сказуемое из двух слов, наречие встаёт после первого: I have never seen… · You should always check… · It will probably work.",
     "more": ""},
    {"n": 10, "title": "Ложные друзья", "bad": "angina, analysis", "good": "tonsillitis, tests",
     "why": "Слово похоже на русское, и кажется, что значит то же самое. Для врача это особенно коварно: angina — это стенокардия, а не ангина.",
     "rule": "Запомни пары, где похожее английское слово значит совсем другое.",
     "ff": [
         {"ru": "ангина", "en": "tonsillitis, a sore throat", "no": "angina", "means": "стенокардия"},
         {"ru": "анализы", "en": "tests, blood tests", "no": "analysis", "means": "разбор, анализ данных"},
         {"ru": "препарат", "en": "drug, medication", "no": "preparation", "means": "обычно «подготовка»"},
         {"ru": "рецепт врача", "en": "prescription", "no": "recipe", "means": "кулинарный рецепт"},
         {"ru": "реанимация (отделение)", "en": "intensive care, ICU", "no": "reanimation", "means": "так не говорят"},
         {"ru": "диагноз", "en": "diagnosis", "no": "diagnose", "means": "глагол «диагностировать»"},
         {"ru": "терапевт", "en": "GP, physician", "no": "therapist", "means": "психотерапевт или физиотерапевт"},
         {"ru": "наркоз", "en": "general anaesthetic", "no": "narcosis", "means": "оглушение (редкий термин)"},
         {"ru": "симпатичный", "en": "nice, good-looking", "no": "sympathetic", "means": "сочувствующий"},
         {"ru": "аккуратный", "en": "careful, neat", "no": "accurate", "means": "точный"},
         {"ru": "актуальный", "en": "relevant, up to date", "no": "actual", "means": "настоящий, фактический"},
         {"ru": "кабинет врача", "en": "office, consulting room", "no": "cabinet", "means": "шкаф; кабинет министров"},
     ],
     "b2": "Ещё: magazine — журнал (магазин — shop), fabric — ткань (фабрика — factory), decade — десятилетие, intelligent — умный, control — управлять, сдерживать (контролировать = check, monitor).",
     "more": ""},
    {"n": 11, "title": "Итог — всё вместе", "rule": "15 случайных карточек из всех десяти ошибок вперемешку."},
]

# Ещё ошибки на пути к B2 (справка): неверно | верно | пояснение
BONUS = [
    ["Is cold today.", "It's cold today.", "подлежащее обязательно: it или there"],
    ["Here is many patients.", "There are many patients here.", "«есть, находится» — there is / there are"],
    ["I'm boring at work.", "I'm bored at work.", "-ed — что я чувствую, -ing — какой предмет"],
    ["I feel myself tired.", "I feel tired.", "feel, relax, concentrate — без myself"],
    ["He said me the news.", "He told me the news.", "say что-то, tell кому-то"],
    ["I did a mistake.", "I made a mistake.", "make a mistake, make a decision"],
    ["during two years", "for two years", "for — сколько времени, during — во время чего"],
    ["in Monday, at the morning", "on Monday, in the morning", "дни — on, части дня — in"],
]

def c(id, t, q, ru, opts, a, why, pick=False, b2=False, also=None):
    d = {"id": id, "t": t, "q": q, "ru": ru, "opts": opts, "a": a, "why": why}
    if pick: d["pick"] = 1
    if b2: d["b2"] = 1
    if also: d["also"] = also
    return d
P = "___"   # карточка «выбери правильную фразу»: вся фраза — это пропуск

CARDS = [
    # 1 · артикли
    c("a1-nurse", 1, "My wife is ___ nurse.", "Моя жена — медсестра.", ["a", "the", ""], "a", "Профессия, одна из многих: a nurse."),
    c("a1-door", 1, "Could you close ___ door, please?", "Закройте, пожалуйста, дверь.", ["the", "a", ""], "the", "Понятно, какая дверь — вот эта: the door."),
    c("a1-smoking", 1, "___ smoking increases the risk of stroke.", "Курение повышает риск инсульта.",
      ["", "The", "A"], "", "Курение вообще, в общем смысле — без артикля. The smoking — ошибка."),
    c("a1-headache", 1, P, "У него болит голова.", ["He has a headache.", "He has headache.", "He has the headache."], "He has a headache.",
      "headache — исчисляемое: a headache, как a cold и a cough.", pick=True),
    c("a1-day", 1, "Take one tablet three times ___ day.", "Принимайте по одной таблетке три раза в день.", ["a", "the", "in"], "a",
      "«В день, в неделю» — a: three times a day. In day — калька с русского."),
    c("a1-results", 1, "Have you seen ___ results of his MRI?", "Ты видел результаты его МРТ?", ["the", "a", ""], "the",
      "Конкретные результаты — его МРТ: the results."),
    c("a1-best", 1, P, "Это лучший вариант лечения.", ["It's the best treatment option.", "It's best treatment option.", "It's a best treatment option."],
      "It's the best treatment option.", "Превосходная степень — всегда the: the best.", pick=True, b2=True),

    # 2 · Present Perfect или Past
    c("pp-yesterday", 2, "I ___ him in the corridor yesterday.", "Я видел его в коридоре вчера.", ["saw", "have seen", "see"], "saw",
      "yesterday — момент в прошлом: Past Simple."),
    c("pp-since", 2, "She ___ in this hospital since 2015.", "Она работает в этой больнице с 2015 года.", ["has worked", "works", "worked"], "has worked",
      "«С 2015-го и до сих пор» — has worked. Works since — ошибка."),
    c("pp-for", 2, P, "Я живу здесь пять лет.", ["I've lived here for five years.", "I live here for five years.", "I'm living here five years."],
      "I've lived here for five years.", "«Уже пять лет, до сих пор» — have + V3 + for.", pick=True),
    c("pp-when", 2, "When ___ you arrive?", "Когда ты приехал?", ["did", "have", "do"], "did",
      "When — вопрос о моменте в прошлом: Past Simple. When have you… — ошибка."),
    c("pp-ever", 2, "Have you ever ___ a case like this?", "Ты когда-нибудь видел такой случай?", ["seen", "saw", "see"], "seen",
      "ever — опыт: Present Perfect, have seen."),
    c("pp-ago", 2, "The symptoms ___ two hours ago.", "Симптомы появились два часа назад.", ["started", "have started", "start"], "started",
      "ago — всегда Past Simple."),
    c("pp-waiting", 2, "I ___ for the lab results for two hours!", "Я жду результаты из лаборатории уже два часа!",
      ["have been waiting", "wait", "am waiting"], "have been waiting", "«Уже два часа жду» — have been + -ing + for.", b2=True),

    # 3 · вопросы без do
    c("qu-where", 3, "Where ___ you work?", "Где ты работаешь?", ["do", "are", ""], "do", "Вопрос с обычным глаголом — нужен do."),
    c("qu-why", 3, P, "Почему ты не позвонил?", ["Why didn't you call?", "Why you didn't call?", "Why you not called?"], "Why didn't you call?",
      "didn't встаёт перед подлежащим: Why didn't you…?", pick=True),
    c("qu-mean", 3, P, "Что значит TIA?", ["What does TIA mean?", "What means TIA?", "What is mean TIA?"], "What does TIA mean?",
      "What does … mean? — с does, а mean без -s.", pick=True),
    c("qu-does", 3, "How often ___ he take his tablets?", "Как часто он принимает таблетки?", ["does", "do", "is"], "does",
      "he — does, а take без -s."),
    c("qu-who", 3, "Who ___ the ambulance?", "Кто вызвал скорую?", ["called", "did called", "does called"], "called",
      "Вопрос к подлежащему (кто?) — без did: Who called?"),
    c("qu-indirect", 3, P, "Не подскажете, где рентген-кабинет?",
      ["Could you tell me where the X-ray room is?", "Could you tell me where is the X-ray room?", "Could you tell me where does the X-ray room?"],
      "Could you tell me where the X-ray room is?", "В косвенном вопросе — обычный порядок слов: where the X-ray room is.", pick=True, b2=True),
    c("qu-time", 3, "Do you know what time ___?", "Вы не знаете, во сколько открывается поликлиника?",
      ["the clinic opens", "does the clinic open", "opens the clinic"], "the clinic opens",
      "Косвенный вопрос — без does и с обычным порядком слов.", b2=True),

    # 4 · will после when и if
    c("wi-when", 4, "I'll call you when I ___ the results.", "Я позвоню тебе, когда получу результаты.", ["get", "will get", "got"], "get",
      "После when — Present Simple, даже о будущем."),
    c("wi-if", 4, "If the pain ___ back, take another tablet.", "Если боль вернётся, выпейте ещё таблетку.", ["comes", "will come", "come"], "comes",
      "После if — Present Simple: comes."),
    c("wi-until", 4, "Stay in bed until the doctor ___.", "Лежите, пока не придёт врач.", ["comes", "will come", "came"], "comes",
      "until — тоже без will."),
    c("wi-soon", 4, P, "Как только придут анализы, мы начнём лечение.",
      ["As soon as the tests come back, we'll start treatment.", "As soon as the tests will come back, we'll start treatment.",
       "As soon as the tests will come back, we start treatment."],
      "As soon as the tests come back, we'll start treatment.", "После as soon as — Present, в главной части — will.", pick=True),
    c("wi-before", 4, "Wash your hands before you ___ the patient.", "Мойте руки, прежде чем осматривать пациента.",
      ["examine", "will examine", "examined"], "examine", "before — без will."),
    c("wi-bp", 4, P, "Если давление будет выше 180, позвоните мне.",
      ["If his blood pressure is over 180, call me.", "If his blood pressure will be over 180, call me.", "If his blood pressure would be over 180, call me."],
      "If his blood pressure is over 180, call me.", "«Если будет» — по-английски if + is.", pick=True),
    c("wi-seen", 4, "I'll call you as soon as I ___ the scan.", "Я позвоню, как только посмотрю снимок.",
      ["have seen", "will see", "will have seen"], "have seen",
      "«Как только посмотрю» — можно Present Perfect: as soon as I've seen. Will — нельзя.", b2=True),

    # 5 · двойное отрицание
    c("ng-anything", 5, "I don't know ___ about his medical history.", "Я ничего не знаю о его анамнезе.",
      ["anything", "nothing", "something"], "anything", "После not — anything. Nothing вместе с not — двойное отрицание."),
    c("ng-nobody", 5, "Nobody ___ me about the allergy.", "Никто не сказал мне про аллергию.", ["told", "didn't tell", "not told"], "told",
      "Nobody — уже отрицание: nobody told me."),
    c("ng-never", 5, P, "Я никогда не видел такой сыпи.",
      ["I've never seen a rash like this.", "I haven't never seen a rash like this.", "I never haven't seen a rash like this."],
      "I've never seen a rash like this.", "never — уже отрицание, not не нужен.", pick=True),
    c("ng-nothing", 5, "The patient said ___ about the pain.", "Пациент ничего не сказал о боли.", ["nothing", "anything", "not nothing"], "nothing",
      "Без not — nothing. Или так: didn't say anything."),
    c("ng-anyone", 5, "I didn't see ___ in the waiting room.", "В приёмной я никого не видел.", ["anyone", "no one", "not anyone"], "anyone",
      "После didn't — anyone. No one вместе с not — двойное отрицание."),
    c("ng-anywhere", 5, P, "Я нигде не могу найти его историю болезни.",
      ["I can't find his notes anywhere.", "I can't find his notes nowhere.", "I can't find nowhere his notes."],
      "I can't find his notes anywhere.", "После can't — anywhere.", pick=True),
    c("ng-hardly", 5, "He ___ breathe.", "Он еле дышит.", ["can hardly", "can't hardly", "hardly can't"], "can hardly",
      "hardly — уже «почти не»: can hardly, без not.", b2=True),

    # 6 · «хочу, чтобы ты…»
    c("wt-want", 6, P, "Я хочу, чтобы ты проверил дозу.", ["I want you to check the dose.", "I want that you check the dose.", "I want you check the dose."],
      "I want you to check the dose.", "want + кого + to + глагол.", pick=True),
    c("wt-let", 6, "Let me ___ the procedure.", "Позвольте, я объясню процедуру.", ["explain", "to explain", "explaining"], "explain",
      "let + кого + глагол без to."),
    c("wt-made", 6, "The tablets made him ___ sick.", "От таблеток его тошнило.", ["feel", "to feel", "feeling"], "feel",
      "make + кого + глагол без to."),
    c("wt-like", 6, "Would you like me ___ your family?", "Хотите, я позвоню вашим родным?", ["to call", "call", "that I call"], "to call",
      "would like + кого + to."),
    c("wt-asked", 6, P, "Медсестра попросила его подождать.", ["The nurse asked him to wait.", "The nurse asked him wait.", "The nurse asked to him to wait."],
      "The nurse asked him to wait.", "ask + кого + to + глагол.", pick=True),
    c("wt-expect", 6, "We don't expect the swelling ___ quickly.", "Мы не ждём, что отёк быстро спадёт.", ["to go down", "go down", "that goes down"],
      "to go down", "expect + что + to + глагол."),
    c("wt-suggest", 6, P, "Предлагаю сделать повторную КТ.", ["I suggest doing a repeat CT.", "I suggest to do a repeat CT.", "I suggest you to do a repeat CT."],
      "I suggest doing a repeat CT.", "suggest + -ing (или suggest that…). Suggest to и suggest you to — ошибки.", pick=True, b2=True),

    # 7 · неисчисляемые
    c("un-advice", 7, "Can I give you ___ advice?", "Можно дать вам совет?", ["some", "an", "many"], "some",
      "advice — неисчисляемое: some advice или a piece of advice."),
    c("un-info", 7, "Thank you for the ___.", "Спасибо за информацию.", ["information", "informations"], "information", "information — без -s."),
    c("un-news", 7, "The news ___ not good, I'm afraid.", "Боюсь, новости плохие.", ["is", "are", "were"], "is", "news — единственное число: the news is."),
    c("un-equipment", 7, P, "Нам нужно новое оборудование.", ["We need new equipment.", "We need new equipments.", "We need a new equipment."],
      "We need new equipment.", "equipment — неисчисляемое: без a и без -s.", pick=True),
    c("un-feedback", 7, "Thanks for your ___ on my talk.", "Спасибо за отзыв о моём докладе.", ["feedback", "feedbacks", "a feedback"], "feedback",
      "feedback — неисчисляемое."),
    c("un-evidence", 7, "There is no ___ that this drug helps.", "Нет доказательств, что этот препарат помогает.", ["evidence", "evidences", "an evidence"],
      "evidence", "evidence — неисчисляемое.", b2=True),
    c("un-research", 7, P, "Он занимается исследованиями инсульта.", ["He does research on stroke.", "He does researches on stroke.", "He does a research on stroke."],
      "He does research on stroke.", "research — неисчисляемое. Одно исследование — a study.", pick=True, b2=True),
    c("un-progress", 7, "The patient is making good ___.", "Пациент хорошо идёт на поправку.", ["progress", "progresses", "a progress"], "progress",
      "progress — неисчисляемое: make good progress.", b2=True),

    # 8 · предлоги-кальки
    c("pr-explain", 8, P, "Объясните мне, пожалуйста, результаты.",
      ["Please explain the results to me.", "Please explain me the results.", "Please explain to me about the results."],
      "Please explain the results to me.", "explain + что + to + кому. Explain me — ошибка.", pick=True),
    c("pr-discuss", 8, "We need to discuss ___ his treatment.", "Нам нужно обсудить его лечение.", ["", "about", "on"], "",
      "discuss — без предлога: discuss the treatment."),
    c("pr-wait", 8, "I'll wait ___ you in the corridor.", "Я подожду тебя в коридоре.", ["for", "", "to"], "for", "wait for someone."),
    c("pr-listen", 8, "Listen ___ his chest.", "Послушай его грудную клетку.", ["to", "", "at"], "to", "listen to."),
    c("pr-enter", 8, "The surgeon entered ___ the room.", "Хирург вошёл в палату.", ["", "into", "to"], "", "enter — без предлога."),
    c("pr-depend", 8, "It depends ___ the results.", "Это зависит от результатов.", ["on", "from", "of"], "on", "depend on, а не from."),
    c("pr-call", 8, "Call ___ me when you get home.", "Позвони мне, когда доберёшься домой.", ["", "to", "at"], "", "call someone — без to."),
    c("pr-arrive", 8, "What time did you arrive ___ the hospital?", "Во сколько ты приехал в больницу?", ["at", "to", "in"], "at",
      "arrive at (здание) или in (город). Arrive to — ошибка.", b2=True),

    # 9 · порядок слов
    c("wo-like", 9, P, "Мне очень нравится эта работа.", ["I really like this job.", "I very like this job.", "I like very much this job."],
      "I really like this job.", "very не ставим перед глаголом; very much — после объекта: I like this job very much.", pick=True),
    c("wo-english", 9, P, "Он очень хорошо говорит по-английски.", ["He speaks English very well.", "He speaks very well English.", "He very well speaks English."],
      "He speaks English very well.", "Глагол и объект вместе — speaks English, потом very well.", pick=True),
    c("wo-always", 9, "I ___ my patients' blood pressure myself.", "Я всегда сам проверяю давление у своих пациентов.",
      ["always check", "check always", "always am checking"], "always check", "always — перед основным глаголом."),
    c("wo-late", 9, "He ___ late for the morning meeting.", "Он часто опаздывает на утреннюю планёрку.", ["is often", "often is", "often"], "is often",
      "С be — наоборот: is often."),
    c("wo-everyday", 9, P, "Я каждый день хожу на работу пешком.", ["I walk to work every day.", "I every day walk to work.", "I walk every day to work."],
      "I walk to work every day.", "Время — в конце: every day.", pick=True),
    c("wo-never", 9, "I have ___ this complication before.", "Я никогда раньше не видел такого осложнения.", ["never seen", "seen never", "never saw"],
      "never seen", "Сказуемое из двух слов — наречие после первого: have never seen.", b2=True),
    c("wo-probably", 9, "It ___ work, but let's try.", "Скорее всего, не сработает, но давай попробуем.",
      ["probably won't", "won't probably", "probably not will"], "probably won't",
      "probably — перед won't, но после will: it will probably work.", b2=True),

    # 10 · ложные друзья
    c("ff-angina", 10, "The child has ___: a sore throat and a high temperature.", "У ребёнка ангина: болит горло и высокая температура.",
      ["tonsillitis", "angina", "angina pectoris"], "tonsillitis", "Ангина — tonsillitis. Angina — стенокардия."),
    c("ff-tests", 10, "We're still waiting for his blood ___.", "Мы всё ещё ждём его анализы крови.", ["tests", "analyses", "analysis"], "tests",
      "Анализы — tests (в больнице говорят и bloods). Analysis — разбор данных."),
    c("ff-careful", 10, "Please be ___ with the dressing — the skin is fragile.", "Пожалуйста, аккуратнее с повязкой — кожа очень тонкая.",
      ["careful", "accurate"], "careful", "Аккуратный, осторожный — careful. Accurate — точный."),
    c("ff-prescription", 10, "The doctor gave me a ___ for antibiotics.", "Врач выписал мне рецепт на антибиотики.",
      ["prescription", "recipe", "receipt"], "prescription", "Рецепт врача — prescription. Recipe — кулинарный рецепт, receipt — чек."),
    c("ff-icu", 10, "After the operation he was taken to ___.", "После операции его отвезли в реанимацию.",
      ["intensive care", "reanimation", "the reanimation"], "intensive care",
      "Реанимация как отделение — intensive care, ICU. Resuscitation — сами реанимационные мероприятия."),
    c("ff-diagnosis", 10, "The final ___ was ischaemic stroke.", "Окончательный диагноз — ишемический инсульт.",
      ["diagnosis", "diagnose", "diagnostic"], "diagnosis", "Диагноз — diagnosis (существительное). Diagnose — глагол."),
    c("ff-gp", 10, "If the headaches continue, see your ___.", "Если головные боли не пройдут, сходите к терапевту.", ["GP", "therapist"], "GP",
      "Участковый терапевт — GP. Therapist — обычно психотерапевт или физиотерапевт."),
    c("ff-nice", 10, "Our new nurse is very ___ — everyone likes her.", "Наша новая медсестра очень симпатичная — все её любят.",
      ["nice", "sympathetic"], "nice", "Симпатичный, приятный — nice. Sympathetic — сочувствующий."),
]

for k in CARDS:
    assert k["a"] in k["opts"] and len(set(k["opts"])) == len(k["opts"]) and k["q"].count("___") == 1, k["id"]
assert len({k["id"] for k in CARDS}) == len(CARDS)

if __name__ == "__main__":
    from collections import Counter
    print(len(CARDS), "cards", sorted(Counter(k["t"] for k in CARDS).items()), "pick:", sum(1 for k in CARDS if k.get("pick")), "b2:", sum(1 for k in CARDS if k.get("b2")))
